### ISSUE TITLE
ERROR Error when sending message to topic XXX with key: null, value: X bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback

### ISSUE THREAD

**Issue by harryge00** [wurstmeister/kafka-docker#100]
I run a local zookeeper-server and run the docker image as:
`docker run -e "KAFKA_ADVERTISED_PORT=9092" -e "KAFKA_ZOOKEEPER_CONNECT=localhost:2181" -p 9092:9092 --net=host  -d wurstmeister/kafka`
Then I tried

```
# bin/kafka-console-producer.sh --broker-list localhost:2181 --topic test
# ERROR Error when sending message to topic test with key: null, value: 6 bytes with error: Batch Expired (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
```

kafka logs:
```
[2016-06-08 09:53:07,783] INFO Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:os.version=4.4.0-22-generic (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,783] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,784] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@1c93084c (org.apache.zookeeper.ZooKeeper)
[2016-06-08 09:53:07,793] INFO Waiting for keeper state SyncConnected (org.I0Itec.zkclient.ZkClient)
[2016-06-08 09:53:07,795] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2016-06-08 09:53:07,834] INFO Socket connection established to localhost/127.0.0.1:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2016-06-08 09:53:07,851] INFO Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x1552f558b520012, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2016-06-08 09:53:07,852] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2016-06-08 09:53:07,978] INFO Log directory '/kafka/kafka-logs-pao-H110M-TS' not found, creating it. (kafka.log.LogManager)
[2016-06-08 09:53:08,009] INFO Loading logs. (kafka.log.LogManager)
[2016-06-08 09:53:08,030] INFO Logs loading complete. (kafka.log.LogManager)
[2016-06-08 09:53:08,109] INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager)
[2016-06-08 09:53:08,110] INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager)
[2016-06-08 09:53:08,113] WARN No meta.properties file under dir /kafka/kafka-logs-pao-H110M-TS/meta.properties (kafka.server.BrokerMetadataCheckpoint)
[2016-06-08 09:53:08,205] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
[2016-06-08 09:53:08,207] INFO [Socket Server on Broker 1003], Started 1 acceptor threads (kafka.network.SocketServer)
[2016-06-08 09:53:08,251] INFO [ExpirationReaper-1003], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2016-06-08 09:53:08,252] INFO [ExpirationReaper-1003], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2016-06-08 09:53:08,277] INFO Creating /controller (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
[2016-06-08 09:53:08,293] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
[2016-06-08 09:53:08,294] INFO 1003 successfully elected as leader (kafka.server.ZookeeperLeaderElector)
[2016-06-08 09:53:08,388] INFO New leader is 1003 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
[2016-06-08 09:53:08,389] INFO [ExpirationReaper-1003], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2016-06-08 09:53:08,390] INFO [ExpirationReaper-1003], Starting  (kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper)
[2016-06-08 09:53:08,398] INFO [GroupCoordinator 1003]: Starting up. (kafka.coordinator.GroupCoordinator)
[2016-06-08 09:53:08,399] INFO [GroupCoordinator 1003]: Startup complete. (kafka.coordinator.GroupCoordinator)
[2016-06-08 09:53:08,400] INFO [Group Metadata Manager on Broker 1003]: Removed 0 expired offsets in 5 milliseconds. (kafka.coordinator.GroupMetadataManager)
[2016-06-08 09:53:08,410] INFO [ThrottledRequestReaper-Produce], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2016-06-08 09:53:08,410] INFO [ThrottledRequestReaper-Fetch], Starting  (kafka.server.ClientQuotaManager$ThrottledRequestReaper)
[2016-06-08 09:53:08,414] INFO Will not load MX4J, mx4j-tools.jar is not in the classpath (kafka.utils.Mx4jLoader$)
[2016-06-08 09:53:08,427] INFO Creating /brokers/ids/1003 (is it secure? false) (kafka.utils.ZKCheckedEphemeral)
[2016-06-08 09:53:08,450] INFO Result of znode creation is: OK (kafka.utils.ZKCheckedEphemeral)
[2016-06-08 09:53:08,451] INFO Registered broker 1003 at path /brokers/ids/1003 with addresses: PLAINTEXT -> EndPoint(pao-H110M-TS,9092,PLAINTEXT) (kafka.utils.ZkUtils)
[2016-06-08 09:53:08,451] WARN No meta.properties file under dir /kafka/kafka-logs-pao-H110M-TS/meta.properties (kafka.server.BrokerMetadataCheckpoint)
[2016-06-08 09:53:08,545] INFO Kafka version : 0.10.0.0 (org.apache.kafka.common.utils.AppInfoParser)
[2016-06-08 09:53:08,545] INFO Kafka commitId : b8642491e78c5a13 (org.apache.kafka.common.utils.AppInfoParser)
[2016-06-08 09:53:08,545] INFO [Kafka Server 1003], started (kafka.server.KafkaServer)
[2016-06-08 10:03:08,395] INFO [Group Metadata Manager on Broker 1003]: Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.GroupMetadataManager)
```

Desribe topic "test":
```
Topic:test	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: test	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
```

**Comment by wurstmeister** [comment]
Hi,

your ```kafka-console-producer.sh``` command line does not look correct.
the ```--broker-list``` argument should point to a broker, not zookeeper like in your example

please see: http://kafka.apache.org/0100/quickstart.html#quickstart_send

**Comment by ssherwood** [comment]
@wurstmeister I'm getting the same error but I'm pretty much following the guide verbatim.

    docker-compose up

Then in another tab

    ./start-kafka-shell.sh 192.168.99.104 192.168.99.104:2181
    bash-4.3# $KAFKA_HOME/bin/kafka-console-producer.sh --topic=topic --broker-list=`broker-list.sh`
    abc
    [2016-06-10 14:08:56,280] ERROR Error when sending message to topic topic with key: null, value:   3 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
    org.apache.kafka.common.errors.TimeoutException: Batch containing 1 record(s) expired due to timeout while requesting metadata from brokers for topic-3

My consumer looks like this:

    ./start-kafka-shell.sh 192.168.99.104 192.168.99.104:2181
    bash-4.3# $KAFKA_HOME/bin/kafka-console-consumer.sh --topic=topic --zookeeper=$ZK

My zookeeper logs look like this during the exchange:

    zookeeper_1  | 2016-06-10 14:10:15,537 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@617] -     Established session 0x1553aa1d9950006 with negotiated timeout 6000 for client /172.18.0.1:51044
    zookeeper_1  | 2016-06-10 14:10:15,598 [myid:] - INFO  [ProcessThread(sid:0   cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing   sessionid:0x1553aa1d9950006 type:create cxid:0x2 zxid:0x1c2 txntype:-1 reqpath:n/a Error   Path:/consumers Error:KeeperErrorCode = NodeExists for /consumers
    zookeeper_1  | 2016-06-10 14:10:15,877 [myid:] - INFO  [ProcessThread(sid:0   cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing   sessionid:0x1553aa1d9950006 type:create cxid:0x1c zxid:0x1c6 txntype:-1 reqpath:n/a Error   Path:/consumers/console-consumer-39205/owners/topic Error:KeeperErrorCode = NoNode for   /consumers/console-consumer-39205/owners/topic
    zookeeper_1  | 2016-06-10 14:10:15,879 [myid:] - INFO  [ProcessThread(sid:0   cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing   sessionid:0x1553aa1d9950006 type:create cxid:0x1d zxid:0x1c7 txntype:-1 reqpath:n/a Error   Path:/consumers/console-consumer-39205/owners Error:KeeperErrorCode = NoNode for   /consumers/console-consumer-39205/owners

And my docker-compose ps:

    docker-compose ps
             Name                        Command               State                         Ports
    ---------------------------------------------------------------------------------------------------------------------
    kafkadocker_kafka_1       start-kafka.sh                   Up      0.0.0.0:32777->9092/tcp
    kafkadocker_zookeeper_1   /bin/sh -c /usr/sbin/sshd  ...   Up      0.0.0.0:2181->2181/tcp, 22/tcp, 2888/tcp, 3888/tcp

**Comment by wurstmeister** [comment]
Hi, 

- what's the output of ````broker-list.sh```?
- do you have any output in the broker log?
- which OS are you using?

**Comment by harryge00** [comment]
I still encounter the [question](http://stackoverflow.com/questions/37761476/kafka-on-kubernetes-cannot-produce-consume-topics-closedchannelexception-error), but I think this is a kubernetes staff.

**Comment by ssherwood** [comment]
@wurstmeister 

My OS is Mac OSX

The output of broker-list:

    bash-4.3# broker-list.sh
    192.168.99.104:32778

I've attached my broker [logs](url
[kafka.txt](https://github.com/wurstmeister/kafka-docker/files/312014/kafka.txt)
)

**Comment by wurstmeister** [comment]
@ssherwood 

what's the output of ```$KAFKA_HOME/bin/kafka-topics.sh --describe --topic topic --zookeeper $ZK```
and does the leader match the ID of the broker (based on your log that's 1010) ? If this is not the case you will see this behaviour. 

It might be worth starting with an clean environment (```docker-compose rm```)

**Comment by ssherwood** [comment]
It looks like it doesn't match:
 
   ➜  kafka-docker git:(master) ✗ ./start-kafka-shell.sh 192.168.99.104 192.168.99.104:2181
    bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --describe --topic topic --zookeeper $ZK
    Topic:topic	PartitionCount:4	ReplicationFactor:2	Configs:
        Topic: topic	Partition: 0	Leader: 1003	Replicas: 1004,1003	Isr: 1003
        Topic: topic	Partition: 1	Leader: 1003	Replicas: 1003,1004	Isr: 1003
        Topic: topic	Partition: 2	Leader: 1003	Replicas: 1004,1003	Isr: 1003
        Topic: topic	Partition: 3	Leader: 1003	Replicas: 1003,1004	Isr: 1003

I did the _docker-compose rm_ and recreated and everything appears to be working now as expected.  Thanks!

**Comment by BlackRider97** [comment]
Not working for me. 
`Error when sending message to topic test with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)`

```
bash-4.3# bin/kafka-topics.sh --describe --zookeeper zookeeper:2181/kafka --topic test
Topic:test	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: analytics-logs	Partition: 0	Leader: 1001	Replicas: 1001	Isr: 1001
```

**Comment by wurstmeister** [comment]
@BlackRider97 the more information you provide the more likely I will be able to help you. 
e.g. steps to reproduce, logs, environment, full error message, ...

**Comment by BlackRider97** [comment]
@wurstmeister  Issue got fixed when I deleted data from zookeeper. 
I tried to upgrade from 0.9 to 0.10 via simply updating docker image.

**Comment by quodt** [comment]
@wurstmeister does this imply, that i should use static (configured) broker ids in production?

**Comment by n1207n** [comment]
I'm having a similar problem here. I pretty much followed the tutorial steps for testing out the kafka running container but I get this error next time I restart the docker container and try to run producer:

`org.apache.kafka.common.errors.TimeoutException: Batch containing 1 record(s) expired due to timeout while requesting metadata from brokers for <TOPIC_NAME>-3`

When the docker container gets a new container id, kafka seems to create a new broker id so the kafka topic from the past is no longer accessible. If you create a brand new topic in the running container again, that topic is accessible as long as the container lives, but is no longer when the container is restarted.

Therefore, I think this is something to do with --no-recreate option in docker-compose in order to keep the same container name/id pair so that kafka keeps same broker_id in its kafka-log meta.properties.

**Comment by Tolsi** [comment]
+1

**Comment by onexdrk** [comment]
+1

**Comment by sudharshankakumanu** [comment]
Hi,

I am facing similar issue 

`[2016-12-01 20:27:44,849] WARN Error while fetching metadata with correlation id 0 : {topic02=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)`

When i describe the topic:
```
Topic:topic02	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: topic02	Partition: 0	Leader: 1001	Replicas: 1001	Isr: 1001
```
```
bash-4.3# ./broker-list.sh 
:32770
```
```
bash-4.3# docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                NAMES
4550654d55ae        wurstmeister/kafka       "start-kafka.sh"         About an hour ago   Up About an hour    0.0.0.0:32770->9092/tcp                              ec2user_kafka_1
1cb984f54d52        wurstmeister/zookeeper   "/bin/sh -c '/usr/sbi"   3 weeks ago         Up 20 hours         22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:2181->2181/tcp   ec2user_zookeeper_1

```
debug steps followed -

- Created brand new topic after starting the docker.
- Cleaned up the environment and even tried reinstalling everything from scratch on a different Ec2.
- Weird thing is that , the same setup was running just fine, from past 2 weeks.

**Comment by sqlcook** [comment]
+1
Having exact same error. 
I'm running macOS 10.12.3 with Docker 1.13.1-rc2-beta41 (15300)
docker-compose template: https://github.com/confluentinc/cp-docker-images/blob/3.1.x/examples/cp-all-in-one/docker-compose.yml

after everything is up i try to produce basic message:
zk_host=localhost
zk_port=2181
broker_host=localhost
broker_port=9092
bin/kafka-avro-console-producer --broker-list ${broker_host}:${broker_port} --topic TestTopic1 --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"f1","type":"string"}]}'
{"f1": "value1"}

receive error:
ERROR Error when sending message to topic TestTopic1 with key: null, value: 12 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback:47)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for TestTopic1-0 due to 1526 ms has passed since batch creation plus linger time

when i run describe:
bin/kafka-topics --describe --topic TestTopic1 --zookeeper ${zk_host}:${zk_port}
Topic:TestTopic1	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: TestTopic1	Partition: 0	Leader: 1	Replicas: 1	Isr: 1

**Comment by karthik-ir** [comment]
+1

**Comment by aiakym** [comment]
+1

**Comment by weisd** [comment]
+1

**Comment by kandeshvari** [comment]
It starts working when I removed zookeeper's data dir `/var/lib/zookeeper/version-2`.

**Comment by lckanth007** [comment]
[cloudera@quickstart kafka_2.11-0.10.2.0]$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
hi
[2017-04-13 18:13:17,793] ERROR Error when sending message to topic test with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for test-0: 1504 ms has passed since batch creation plus linger time
^C[cloudera@quickstart kafka_2.11-0.10.2.0]$

**Comment by lckanth007** [comment]
How to resolve it .?


[cloudera@quickstart kafka_2.11-0.10.2.0]$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
hi
[2017-04-13 18:13:17,793] ERROR Error when sending message to topic test with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for test-0: 1504 ms has passed since batch creation plus linger time
^C[cloudera@quickstart kafka_2.11-0.10.2.0]$

**Comment by keerthivasan-r** [comment]
I 'm also getting the same error @lckanth007 Were you able to fix it? I'm just doing the quick start tutorial in documentation. I'm just running in my windows 10 local machine. Somebody help! 😕

**Comment by hao5ang** [comment]
@keerthivasan-r 
I use `docker Kafka` and `docker Zookeeper`. I just leave `Kafka` alive and restart `Zookeeper`. After that, every thing goes well.   
I got `org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms` Exception.

**Comment by javierholguera** [comment]
I'm getting the same error using Windows 8.1 and docker-toolbox.

**Comment by keerthivasan-r** [comment]
@hao5ang How is that possible? Zookeeper has to register the kafka brokers right. Does that not clear the registries of kafka brokers list at zookeeper? Please clarify

**Comment by keerthivasan-r** [comment]
Adding to that, I'm getting the problem even outside docker environment. I.e plain vanilla kafka deployment

**Comment by hao5ang** [comment]
@keerthivasan-r I'm so sorry, my exception can not be reproduced. I am not familiar with Kafka.

**Comment by irisrain** [comment]
kafka-console-producer.sh nonsupport key=null .. so use api test

**Comment by irisrain** [comment]
You may be setting log.cleanup.policy=compact . This must use key and value
kafka-console-producer.sh nonsupport key=null .. so use api test

**Comment by Shabirmean** [comment]
I am getting the same error in a plain vanilla download (without docker) and when I follow the quick start guide for the latest version of kafka. I switched back to 2.11-0.9.0.1 since I wanted to get working quick..

If anybody has a resolution for this please do reply...

**Comment by Shabirmean** [comment]
I was able to overcome the issue by modifying:
**listeners=PLAINTEXT://hostname:9092** property in the _server.properties_ file to
**listeners=PLAINTEXT://0.0.0.0:9092**

I don't have any idea what it does but it works...

**Comment by maheshveera** [comment]
Could someone reopen this issue? I am facing the same issue and tried everything discussed here but still the issue is not resolved

**Comment by MoJo2600** [comment]
I had the exact same problem as @n1207n mentioned. But @Shabirmeans fix did not help me.

I have kafka deployed in Kubernetes. One kafka broker and 3 zookepper nodes. I created a topic and was able to produce/consume messages. After a restart of the kafka container, i could not post to existing topics anymore but newly created topics worked fine. I found out, that the old topic was bound to broker 1001, but the new broker had the id 1006 (after some restarts).

What i did was to reset the broker.id back to 1001 and then i was able to produce messages on the old topic again. I set the brocker.id back by setting the environment variable KAFKA_BROKER_ID to 1001.

I'm not sure if this is the correct way to fix the issue, but it worked.

**Comment by litongyu** [comment]
I have tried @MoJo2600 's solution and it works! Just set the KAFKA_BROKER_ID in docker-compose.yml.

**Comment by smehtaji** [comment]
I have the same issue while trying to produce and consume at two different terminals 
`[root@sandbox kafka-broker]# bin/kafka-console-producer.sh --broker-list localhost:9092 --topic test
sandee
[2017-07-11 12:23:15,929] ERROR Error when sending message to topic test with key: null, value: 6 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
`

**Comment by litongyu** [comment]
@smehtaji try public ip address instead of localhost

**Comment by steverhoades** [comment]
@litongyu @MoJo2600 I'm also on OSX.  I tried adding KAFKA_BROKER_ID=1001 and it barfed with...
```
kafka_1      | [2017-08-02 21:17:44,141] FATAL  (kafka.Kafka$)
kafka_1      | java.lang.IllegalArgumentException: requirement failed: broker.id must be equal or greater than -1 and not greater than reserved.broker.max.id
kafka_1      | 	at scala.Predef$.require(Predef.scala:277)
kafka_1      | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1159)
kafka_1      | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1155)
kafka_1      | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:867)
kafka_1      | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:864)
kafka_1      | 	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1      | 	at kafka.Kafka$.main(Kafka.scala:58)
kafka_1      | 	at kafka.Kafka.main(Kafka.scala)
kafkadocker_kafka_1 exited with code 1
```
This is interesting because the output of kafka-topics is....
```
bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --describe --topic test --zookeeper $ZK
Topic:test	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: test	Partition: 0	Leader: 1001	Replicas: 1001	Isr: 1001
```

Any advice on how to move forward?  I am trying to solve this error
```
bash-4.3# $KAFKA_HOME/bin/kafka-console-producer.sh --topic=test --broker-list=`broker-list.sh` --property print.key=true --property key.separator=, 
>key 1, message foo
[2017-08-02 20:24:14,183] ERROR Error when sending message to topic test with key: null, value: 18 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
>[2017-08-02 20:25:26,974] WARN Connection to node -1 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
```

**Comment by litongyu** [comment]
@steverhoades The error messages mean that your broker id 1001 exceeds the broker.max.id(default 1000), so just set the KAFKA_BROKER_ID = 999. Good luck!

**Comment by steverhoades** [comment]
@litongyu thanks, i banged my head on this one for hours and finally gave up.  Used this one https://hub.docker.com/r/ches/kafka/ and was up and running in minutes.  Still not entirely sure where I went wrong with wurstmeister's docker image...

**Comment by MoJo2600** [comment]
@steverhoades You are able to set the maximum allowed broker id by setting the KAFKA_RESERVED_BROKER_MAX_ID environment variable.

**Comment by softwarevamp** [comment]
-e KAFKA_ADVERTISED_HOST_NAME=127.0.0.1 works for me.

**Comment by ERPChina** [comment]
I finally make it work in kubernetes v1.6 with this image, but with minor modifications. 
My lesson learnt as below:
1. advertised.listeners should provide 2 listeners, one with internal ip and port 9093 for controller to connect with broker in the same pod, one external service ip for client to connect
2. check the configuration and make sure zookeeper and kafka run successfully, then redeploy them to have a clean environment, it might be the reason for timeout exception during message producing

**Comment by artemyarulin** [comment]
Found issue in my case - I'm using `cleanup.policy=compact` config in one channel and for some reason `kafka-console-producer` doesn't work with such channels, am I doing something wrong? Normal channels works just fine

``` bash
$ kafka-topics --create --zookeeper "zookeeper-0.zookeeper" --partitions 1 --replication-factor 1 --topic topicA
Created topic "topicA".
$ kafka-topics --describe --zookeeper "zookeeper-0.zookeeper" --topic topicA
Topic:topicA	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: topicA	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
$ echo hello | kafka-console-producer --broker-list "localhost:9092" --topic "topicA" 
$ kafka-topics --create --zookeeper "zookeeper-0.zookeeper" --partitions 1 --replication-factor 1 --topic topicB --config cleanup.policy=compact
Created topic "topicB".
$ kafka-topics --describe --zookeeper "zookeeper-0.zookeeper" --topic topicB
Topic:topicB	PartitionCount:1	ReplicationFactor:1	Configs:cleanup.policy=compact
	Topic: topicB	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
$ echo hello | kafka-console-producer --broker-list "localhost:9092" --topic "topicB" 
[2018-01-13 10:46:39,295] WARN [Producer clientId=console-producer] Got error produce response with correlation id 3 on topic-partition topicB-0, retrying (2 attempts left). Error: CORRUPT_MESSAGE (org.apache.kafka.clients.producer.internals.Sender)
[2018-01-13 10:46:39,397] WARN [Producer clientId=console-producer] Got error produce response with correlation id 4 on topic-partition topicB-0, retrying (1 attempts left). Error: CORRUPT_MESSAGE (org.apache.kafka.clients.producer.internals.Sender)
[2018-01-13 10:46:39,503] WARN [Producer clientId=console-producer] Got error produce response with correlation id 5 on topic-partition topicB-0, retrying (0 attempts left). Error: CORRUPT_MESSAGE (org.apache.kafka.clients.producer.internals.Sender)
[2018-01-13 10:46:39,611] ERROR Error when sending message to topic topicB with key: null, value: 5 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.CorruptRecordException: This message has failed its CRC checksum, exceeds the valid size, or is otherwise corrupt.
```

**Comment by artemyarulin** [comment]
Ah, stupid me, when compaction it turned on key is required, so correct way to fill such channel from bash is:
``` bash
echo "hello:world" | kafka-console-producer \
  --broker-list "localhost:9092" \
  --topic "topicB" \
  --property "parse.key=true" \
  --property "key.separator=:"
```

Just found @irisrain comment about that in this thread, thank you!

**Comment by bat9r** [comment]
I solve this problem, after edit /etc/hosts
` <ip address current machine> localhost localhost.localdomain`

**Comment by jpavanaryan** [comment]
I faced almost all the problems mentioned above. Following steps worked for me. I ran these on the host machine. 
1. Add the user to the docker group.
`sudo usermod -aG docker $(whoami)`
2. Log out and log back in to ensure docker runs with correct permissions.
3. Start docker.
  ` sudo service docker start`

**Comment by orefalo** [comment]
Setting
```
    KAFKA_ADVERTISED_HOST_NAME: 'kafka.docker.ssl'
      KAFKA_BROKER_ID: 999
```
Fixed this issue!!!

Full working code at https://github.com/orefalo/docker-kafka-ssl

**Comment by jkilgrow** [comment]
> You may be setting log.cleanup.policy=compact . This must use key and value
> kafka-console-producer.sh nonsupport key=null .. so use api test

What does this mean? It seems like you are making some assumptions that people have a clue what you mean by "...so use api test.." Can you elaborate on this?

**Comment by FanJunling** [comment]
I received the same error like below:
[2018-12-03 13:44:24,392] ERROR Error when sending message to topic fan with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for fan-2: 1544 ms has passed since batch creation plus linger time
[2018-12-03 13:44:25,561] ERROR Error when sending message to topic fan with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for fan-1: 1521 ms has passed since batch creation plus linger time
[2018-12-03 13:44:26,829] ERROR Error when sending message to topic fan with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for fan-0: 1540 ms has passed since batch creation plus linger time

I'm in other VM to connect the Kafka brokers. 
Then I modify the /etc/hosts file to add the same hosts both in Brokers and the test VM. And it works.

**Comment by doakinyemi** [comment]
Can confirm that updating /etc/hosts does appear to resolve the issue. Thanks for the recommendation!

**Comment by TKENGG** [comment]
We tried everything, but no luck.

1. Decreased producer batch size and increased request.timeout.ms.
2. Restarted target kafka cluster, still no luck.
3. Checked replication on target kafka cluster, that as well was working fine.
4. Added retries, retries.backout.ms in prodcuer properties.
5. Added linger.time as well in kafka prodcuer properties.

Finally our case there was issue with kafka cluster itself, from 2 servers we were unable to fetch metadata in between.

When we changed target kafka cluster to our dev box, it worked fine.

**Comment by Fakhruddin-Kararawala** [comment]
> Found issue in my case - I'm using `cleanup.policy=compact` config in one channel and for some reason `kafka-console-producer` doesn't work with such channels, am I doing something wrong? Normal channels works just fine
> 
> ```shell
> $ kafka-topics --create --zookeeper "zookeeper-0.zookeeper" --partitions 1 --replication-factor 1 --topic topicA
> Created topic "topicA".
> $ kafka-topics --describe --zookeeper "zookeeper-0.zookeeper" --topic topicA
> Topic:topicA	PartitionCount:1	ReplicationFactor:1	Configs:
> 	Topic: topicA	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
> $ echo hello | kafka-console-producer --broker-list "localhost:9092" --topic "topicA" 
> $ kafka-topics --create --zookeeper "zookeeper-0.zookeeper" --partitions 1 --replication-factor 1 --topic topicB --config cleanup.policy=compact
> Created topic "topicB".
> $ kafka-topics --describe --zookeeper "zookeeper-0.zookeeper" --topic topicB
> Topic:topicB	PartitionCount:1	ReplicationFactor:1	Configs:cleanup.policy=compact
> 	Topic: topicB	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
> $ echo hello | kafka-console-producer --broker-list "localhost:9092" --topic "topicB" 
> [2018-01-13 10:46:39,295] WARN [Producer clientId=console-producer] Got error produce response with correlation id 3 on topic-partition topicB-0, retrying (2 attempts left). Error: CORRUPT_MESSAGE (org.apache.kafka.clients.producer.internals.Sender)
> [2018-01-13 10:46:39,397] WARN [Producer clientId=console-producer] Got error produce response with correlation id 4 on topic-partition topicB-0, retrying (1 attempts left). Error: CORRUPT_MESSAGE (org.apache.kafka.clients.producer.internals.Sender)
> [2018-01-13 10:46:39,503] WARN [Producer clientId=console-producer] Got error produce response with correlation id 5 on topic-partition topicB-0, retrying (0 attempts left). Error: CORRUPT_MESSAGE (org.apache.kafka.clients.producer.internals.Sender)
> [2018-01-13 10:46:39,611] ERROR Error when sending message to topic topicB with key: null, value: 5 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
> org.apache.kafka.common.errors.CorruptRecordException: This message has failed its CRC checksum, exceeds the valid size, or is otherwise corrupt.
> ```

working fine for me when removing compact policy
